### ISSUE TITLE
Doesn't work if the color at input coordinates is black

### ISSUE THREAD

**Issue by tcatsl** [karlew/canvas-flood-fill#1]
For some reason, it seems that the flood fill does not work if the color at input coordinates is black. Have tried this with different tolerances. For reference, see my implementation of your code at https://github.com/tcatsl/NodeMousetrackDrawchat/blob/master/assets/scripts/draw.js line 186. (I did credit you in the Readme of the project)

**Comment by tcatsl** [comment]
I see where you specify this in the code now. Removed for my purposes. Sorry for bothering you, and thanks for making the repo!

**Comment by karlew** [comment]
I forgot to reply to you last year. Thank you for your feedback. Bug has been repaired but it is a pity that color the line is not available now (You can't change the color of the line) , and I didn't find a good solution.
By The Way, your project NodeMousetrackDrawchat is interesting

**Comment by karlew** [comment]
@tcatsl I forgot to reply to you last year. Thank you for your feedback. The bug has been repaired but it is a pity that color the line is not available now (You can't change the color of the line) , and I didn't find a good solution.
By The Way, your project NodeMousetrackDrawchat is interesting.
